name: "Robot"
L1: 228 #mm
L2: 136.5 #mm
base_speed: 500 #2000 is max
base_acceleration: 1000  #4000 is max
base_tcp_vel: 1 # mm/s
base_accuracy: 0.1 # Either degrees or mm depending on the unit for the joint

# How many steps one degree corresponds to in the motors, in the case of z it's mm instead of degrees.
J1_angle_to_steps: 44.444444
J2_angle_to_steps: 35.555555
J3_angle_to_steps: 10
z_mm_to_steps: 100

# Max and min values for the joints, gripper, z-axis, velocity and acceleration
z_max: 150
z_min: 0

J1_max: 3 
J1_min: -3

J2_max: 3
J2_min: -3

J3_max: 3
J3_min: -3

gripper_max: 40
gripper_min: 0

v_max: 2000
v_min: 0

a_max: 4000
a_min: 0

limit_epsilon: 1.0e-12 # For when checking if min or max values are complied with. 

imaginary_epsilon: 1.0e-5 # Due to numerical errors(I hope), J2 sometimes becomes complex when calculating inverse kinematics. This is for how much "complexity" is allowed 

base_radius: 60 # The radius of the part of the robot base that turns

dx: 1 # How fine to linear interpolate. with x0 = 0 and x1 = 1, there will be dx steps between x0 and x1.