name: "G-Code"

# Path for g-code file to load
base_path: "g_code.gcode"

# Robot params
tcp_vel: 3
accuracy: 0.1


x_base_offset: 100
y_base_offset: 0
z_base_offset: 0

dtheta: 0.01 # How many steps there are between two radians. Between 0 and 1 there is dtheta number of steps
